[workspace]
resolver = "2"
members = [
    "quorum-core",
    "quorum-public",
    "quorum-private",
]

[workspace.package]
edition = "2024"

[profile.dev]
opt-level = 0
debug = 1
incremental = true
codegen-units = 256

[profile.release]
opt-level = "z"
lto = "fat"
codegen-units = 1
panic = "abort"
strip = "symbols"