[package]
name = "quorum-private"
version = "0.1.0"
edition.workspace = true

[dependencies]
quorum-core = { path = "../quorum-core" }
axum = { version = "0.8.9", features = ["macros"] }
serde = { version = "1.0.228", features = ["derive"] }
serde_json = "1.0.150"
tokio = { version = "1.52.3", features = ["full", "signal"] }
tower = "0.5.3"
tower-http = { version = "0.7.0", features = ["cors", "trace", "set-header"] }
tracing = "0.1.44"
tracing-subscriber = "0.3.23"
dotenvy = "0.15.7"
surrealdb = { version = "3.1.5", features = ["kv-rocksdb"] }
colored = "3.1.1"
surrealdb-types = "3.1.5"
jsonwebtoken = "10.4.0"
chrono = "0.4.45"
tower_governor = "0.8.0"
rpassword = "7.5.4"
arc-swap = "1.9.1"
http = "1.4.2"