services:
  surrealdb:
    image: surrealdb/surrealdb:v3.1.5
    user: root
    command: start --user ${SURREAL_ROOT_USER} --pass ${SURREAL_ROOT_PASS} --bind 0.0.0.0:8000 surrealkv:///data/quorum.db
    ports:
      - "8000:8000"
    volumes:
      - surreal_data:/data
    environment:
      - SURREAL_ROOT_USER=${SURREAL_ROOT_USER}
      - SURREAL_ROOT_PASS=${SURREAL_ROOT_PASS}

volumes:
  surreal_data: