services:
  surrealdb:
    image: surrealdb/surrealdb:v3.1.5
    user: root
    command: start --user ${SURREAL_ROOT_USER} --pass ${SURREAL_ROOT_PASS} --bind ${SURREAL_BIND} surrealkv:///data/quorum.db
    ports:
      - "8000:8000"
    volumes:
      - surreal_data:/data
    environment:
      - SURREAL_ROOT_USER=${SURREAL_ROOT_USER}
      - SURREAL_ROOT_PASS=${SURREAL_ROOT_PASS}
      - SURREAL_BIND=${SURREAL_BIND}

  minio:
    image: minio/minio:latest
    command: server /data --console-address ":9001"
    ports:
      - "9000:9000"
      - "9001:9001"
    environment:
      MINIO_ROOT_USER: minioadmin
      MINIO_ROOT_PASSWORD: apple
    volumes:
      - minio_data:/data

volumes:
  surreal_data:
  minio_data: